# Generated by Django 4.1 on 2022-08-31 19:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_Name", models.CharField(max_length=200)),
                ("price", models.FloatField(blank=True, default=0.0)),
                ("product_discriptions", models.TextField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
